# Generated by Django 2.0.3 on 2018-03-31 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_no',
            field=models.IntegerField(default=9999999999, validators=[django.core.validators.MinValueValidator(7777777777), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
